### PR TITLE
Switch to umd dist and uglify

### PR DESCRIPTION
**Pull request by flynfish**
Switches to a UMD distribution and uglifies it.

### CODE REVIEW

**Comment by blackbing** [comment]
cool, thanks.

**Comment by blackbing** [comment]
@flynfish thanks for your contributing. I published it to 0.2.0, nice work.

**Comment by flynfish** [comment]
@blackbing no worries! In the process of doing this, I discovered if you change the default format there are bugs with numeral.js. I'd recommend switching from numeral to [numbro.js](http://numbrojs.com/) since numeral isn't maintained anymore.

**Comment by blackbing** [comment]
@flynfish , thanks for this update. I tried to use [numbro.js](http://numbrojs.com/), but I can't fix its dependency right away. I will also upgrade node version to 4.0 and try to merge this package in the future. Thanks again. (y)

**Pull request merged**
